### ISSUE TITLE
Battery power option?

### ISSUE THREAD

**Issue by SteveNewhouse** [lspr98/profitec-go-waterlevel-shottimer#4]
Might it be possible to adapt this for a battery-powered option in case there are ppl less comfortable tapping the machine power?  Could something like this work? https://www.amazon.com/gp/product/B099P95JPH/ref=ewc_pr_img_2?smid=AYZMETEBRR587&psc=1

**Comment by lspr98** [comment]
Hey Steve,

it probably would work, but you will be on your own to try that out. The system draws around 1W when the display is on, so your power supply should at least be able to handle that (AA batteries should be able capable of more). If you have a look at the wiring diagram, you simply have to replace the mains-powered power supply with your power supply.

<img width="407" alt="Screenshot 2024-09-28 092823" src="https://github.com/user-attachments/assets/7388b2d7-60d8-4b8a-afd5-ffcb1d31cdcc">

I don't know how much the system is drawing on average when in standby, hence I can't give you an estimate on how often you will have to swap batteries. Another possible option would be to use an old phone charger with a USB-A port and an old USB-A cable (that way you don't need to open your machine or handle mains voltage and you don't need to replace batteries). 

Going with a battery-powered solution just replaces one problem with another. Instead of having to look after the fill-level of the espresso machine, you now have to look after the batteries of the fill-level sensor. But it's open-source and you can build whatever you want out of it ;)

**Comment by SteveNewhouse** [comment]
Thank you

**Comment by SteveNewhouse** [comment]
Follow up - sorry for bothering... I went with the USB idea you mentioned, but I used a USB-C instead of USB-A.  I've found that even connecting the red/black power/ground lines directly to the soldered wires on the display (for testing), it does not power up... Eyeballing the display soldering, it looks correct with no bridging, and when I plug a USB-C directly into the port on the display, it works (so the unit is not broken)... Could it be a voltage issue with USB-C vs USB-A?

**Comment by lspr98** [comment]
Hey Steve,

USB-C is tricky, since often there is some sort of communication between the charger and the device necessary to decide on the output voltage. It could very well be a voltage issue, as you pointed out correctly.

Did you per chance measure the voltage across the red (+5V) and black (GND) cables while the other end is plugged in? If you don't get 5V it may be an issue with the charger not getting any feedback from the device and hence not delivering any output voltage. In that case you may need to solder an additional sensing-resistor to the wires (but I am really not an expert regarding USB-C).

You could also measure the voltage across the two cables while the display is powered via the USB-C port on the display (make sure the other end of the cable that you soldered to the display is unplugged!). If you then measure 5V across the two solder joints where the red and black cables are soldered to, you know that you got the correct pins.

In all cases, take care that you never connect the display from both sides simultaneously to a power source, otherwise you may ruin the display or your devices.

**Comment by SteveNewhouse** [comment]
Yeah- using a simple USB-A cable it works!  Thank you for all your help!
